global:
  scrape_interval: 5s
  external_labels:
    monitor: 'product-micro' 

scrape_configs:
  - job_name: 'product-micro'
    scrape_interval: 4s
    static_configs:
      - targets: ['localhost:$PORT']